apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: kuber-demo
    image: visualpath/kuber-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
